'use client';
import { useState } from 'react';
import type { Finding } from '@/lib/analyze';
type Result = { chars: number; findings: Finding[]; jev: null | { tone: 'low' | 'medium' | 'high'; repetition: number }; message?: string };
const sample = '随后，克莱恩意识到，眼前的线索并不简单——它像一把钥匙，打开了另一个问题。由此判断，他必须重新梳理结论：那些看似偶然的细节、陌生的脚步、突兀的沉默，或许都指向同一件事。\n\n他停在门前，听见屋里有人轻轻咳了一声。门把手冰凉。';
export default function Home() {
  const [text, setText] = useState(''); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit() { setLoading(true); setError(''); setResult(null); try { const response = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || '检测失败'); setResult(data); } catch (e) { setError(e instanceof Error ? e.message : '检测失败'); } finally { setLoading(false); } }
  const tone = result?.jev?.tone;
  return <main><header><a className="wordmark" href="/">纸间<span> / </span>观察室</a><span className="edition">NOVEL TONE LAB · 01</span></header><section className="hero"><div className="eyebrow"><span className="dot"/> 给小说做一次文本体检</div><h1>读出文字里的<br/><em>机械味。</em></h1><p>粘贴一段中文小说，观察重复、解释和模板化表达留下的痕迹。每个提示都对应原文，方便你自己判断。</p></section><section className="workspace"><div className="section-heading"><div><span className="step">01 / 输入片段</span><h2>把文字放在这里</h2></div><span className="hint">80–6000 字 · 不保存输入</span></div><textarea value={text} onChange={e => setText(e.target.value)} placeholder="粘贴一段小说正文……" aria-label="小说片段"/><div className="actions"><button className="sample" onClick={() => { setText(sample); setResult(null); }}>填入示例</button><span className="counter">{text.length} / 6000</span><button className="primary" disabled={loading || text.trim().length < 80 || text.length > 6000} onClick={submit}>{loading ? '正在观察…' : '开始观察'} <span>↗</span></button></div>{error && <p className="error" role="alert">{error}</p>}</section>{result && <section className="results"><div className="section-heading"><div><span className="step">02 / 观察结果</span><h2>先看证据，再下判断</h2></div><span className="hint">{result.chars} 个汉字 · {result.findings.length} 处规则命中</span></div><div className="verdict"><div><span className="small-label">JEV 文风判断</span><strong>{tone ? ({ low: '机械感较低', medium: '局部机械感', high: '机械感较明显' })[tone] : '暂未启用'}</strong><p>{result.message || '这是对文风的观察，不是“AI 写作概率”或作者身份鉴定。'}</p></div>{result.jev && <div className="metric"><b>{Math.round(result.jev.repetition * 100)}%</b><span>重复解释倾向<br/>Jev 判断概率</span></div>}</div><div className="finding-list">{result.findings.length ? result.findings.map((f, i) => <article key={i} className="finding"><span className="number">{String(i + 1).padStart(2, '0')}</span><div><h3>{f.title}</h3><blockquote>“{f.excerpt}”</blockquote><p>{f.note}</p></div></article>) : <p className="empty">这段文字没有命中当前规则。没有命中不代表它一定没有机械味。</p>}</div></section>}<footer><p>依据本仓库《诡秘之主》57 章同章对照设计。规则提示具有文体和样本边界，请结合上下文阅读。</p><a href="https://github.com/Manytw2/novel-ai-tone" target="_blank" rel="noreferrer">查看研究与源码 ↗</a></footer></main>;
}
